### ISSUE TITLE
Simplify user interface

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#19]
This series of buttons could be summarized into a single drop-down menu named "Plot shortcuts":
![image](https://user-images.githubusercontent.com/9883832/176880208-3d486541-950a-4e1e-9c7b-f3f1f6fa50db.png)

"Plot shortcuts"
"Erase all", "Show all", "Last 2 years", "Last 5 years", etc...

**Comment by TomLav** [comment]
As we discussed, "Plot shortcuts" could be a text above the menu, so that the user can read its current selected stage from the menu.

**Comment by huaracheguarache** [comment]
@TomLav Do you still want me to implement the functionality you describe in the previous comment? I'm not sure that's the best way to do things because it wouldn't properly track the state of the visualisation. That would lead to a difference between what's been selected in the plot shortcut and what's actually shown in some situations. Here's an example:

1. A user selects the last 2 years under plot shortcut.
2. After that the user unhides a few additional years.
3. The plot shortcut still shows "Last 2 years".

**Comment by TomLav** [comment]
I see your concern. What about we rename "plot shortcut" to "plot action"?
Then it conveys it is a one-time thing?

fredag 30. september 2022 skrev Michael Yartys ***@***.***>:

**Comment by TomLav** [comment]
We go for your idea.
