### ISSUE TITLE
Can we build the visualization from a URL?

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#41]
Could the choice of plotting options (area, plot shortcut, time shortcut, color schemes, etc...) be controlled from parameters in the URL? This would allow ppl to directly access their preferred plot setup without too much clicking.

Ideally this should also work when the URL starts with cryo.met.no or osisaf.met.no ...

**Comment by epifanio** [comment]
You can pass parameters to the URL and use such parameters to customize the app settings - so answer is yes.

it can look something like:

https://seaice.metsis-api.met.no/SIE?zoom_shortcuts='value'&index='sea ice area' ... and so on.

potentially is possible to save the GUI settings in a url string so that a user can reuse-share it

**Comment by huaracheguarache** [comment]
This is just for the purposes of housekeeping for me. We would need to add parameters to keep track of the following in the URL:

* Index
* Area
* Reference period
* Which glyphs are currently visible
* Zoom
* Colour scale

**Comment by huaracheguarache** [comment]
As discussed with @TomLav, it might be a good idea to create a share button to copy the link with the current parameter settings for easier sharing by the user.

**Comment by huaracheguarache** [comment]
Basic functionality has been implemented in #87, but currently there is no share button, and custom glyph selection is not supported.

**Comment by TomLav** [comment]
Implemented as good as we can for now. We can re-open issues if we want to improve on the URL-aspects.
