### ISSUE TITLE
Problem: the latest data point is not always plotted

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#48]
Sometimes (often?) the most recent data point in the thredds file is not plotted, as if there was a caching mechanism. This is the case even if we reload the browser tab (but not if we open the vewier in another browser).

Investigate if we understand where this comes from, can it be reproduced?

If we do not find a better solution, add a button or a many choice to "Re-read data". It could e.g. be one of the alternatives in the "Plot actions" menu.

**Comment by huaracheguarache** [comment]
During my testing I noticed that the issue only appears to happen when we're looking at SIE for Northern Hemisphere, every other combination works fine and plots yesterday's data (tested 2022-09-21T14:15). I'm not able to reproduce the issue when I run the Bokeh app locally so I think the first thing worth trying is to just update the version on the server to be in line with the prototype branch.

There's no caching going on in the Bokeh app, but does thredds somehow cache stuff? The only data which seems to be affected is SIE for Northern Hemisphere which would logically be the data that's requested the most from thredds. Could thredds be doing something wonky because of a high number of requests from one IP?

**Comment by huaracheguarache** [comment]
I've disabled xarray caching in #50. Now we just need to deploy the latest version to the server to test whether it fixes the issue.
