### ISSUE TITLE
Investigate time-axis from e.g. July to June

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#67]
Investigate how to change the time-axis of the plot so that it covers July-Dec-Jan-June

**Comment by huaracheguarache** [comment]
One potential solution to the issue I envisioned was to plot with a periodic x-range that would allow you to pan infinitely through the x-axis, but Bokeh unfortunately doesn't support this.

**Comment by TomLav** [comment]
That would indeed have been a neat solution... If Bokeh doesn't support this, do we then have to manipulate the data itself before the plotting? I am interested to review your attempt a look before you change everything :) tell me.

**Comment by TomLav** [comment]
After discussing more with Signe, I want to emphasize that the curves shouldn't change color past Jan 1st. What we want to plot is "1-year worth" of data (~365 days) starting at e.g. July 1st. This "worth of data" will get one color, and the line label (for the legend) could be e.g. "2006/07" (if the line starts July 1st 2006 and ends June 30th 2007).

Maybe this simplifies things a bit. Once we've read the 40+ years of data, instead of organize them by individual years (https://github.com/metno/sea-ice-index-viz/blob/3e51c22dd7623797343fd71d7975af28c3921699/bokeh-app/toolkit.py#L122) we can rather organize them into a series of [July 1st YYYY; June 30th YYYY+1] chunks, and use these chunks in the plotting?

**Comment by huaracheguarache** [comment]
This issue turned out to be quite challenging, and the reasons for this are the following:

* We need to re-organise the years such that they start on July 1st and end at June 30th. Say we originally have a dataset consisting of 3 years, for example 2000, 2001, 2003, where 2003 is the current year. If the last date with data for 2003 is before July 1st then we get 4 years worth of data with the re-organised years (1999-2000, 2000-2001, 2001-2002, 2002-2003), and if it's at or after July 1st we get 5 years worth of data (1999-2000, 2000-2001, 2001-2002, 2002-2003, 2003-2004). Adding and removing glyphs in Bokeh is not recommended and can often lead to buggy behaviour as it's designed to update the underlying data used to plot existing glyphs instead.

* Adding or removing glyphs also greatly complicates the plot callbacks that hide or show different glyphs.

**Comment by TomLav** [comment]
Wont' fix
